# Copyright DIMSI

parameters:

  - name: PowerPlatformSPN
    displayName: Service connection to PowerPlatform
    type: string

  - name: sourceEnvironment
    displayName: Source environment
    type: object
    default: []

  - name: destinationEnvironment
    displayName: Destination environment
    type: object
    default: []

  - name: backupDestinationEnvironment
    displayName: Do we need to extract solutions to the repository
    type: boolean
    default: false

  - name: DisableAdminMode
    displayName: Disable admin mode in destination environment
    type: boolean
    default: false

  - name: CopyType
    displayName: Copy type (either full or minimal)
    type: string
    default: 'MinimalCopy'

  - name: preparationUsersteps
    type: stepList
    default: []

  - name: beforeCopyEnvironmentUsersteps
    type: stepList
    default: []

  - name: afterCopyEnvironmentUsersteps
    type: stepList
    default: []

stages:
  - stage: Preparation
    displayName: Preparation
    jobs:
      - job: Preparation
        steps :

          - checkout: self
            persistCredentials: true
            fetchDepth: 0
            clean: true

          - task: XrmFrameworkConnectionStringsCreation@1
            inputs:
              authenticationType: 'PowerPlatformSPN'
              PowerPlatformSPN: '${{ parameters.PowerPlatformSPN }}'

          - ${{ each step in parameters.preparationUsersteps }}:
            - ${{ each pair in step }}:
                ${{ pair.key }}: ${{ pair.value }}

  - stage: CopyEnvironment
    displayName: Copy ${{parameters.sourceEnvironment}} to ${{ parameters.destinationEnvironment.name }}
    jobs:
      - job: CopyEnvironment
        steps:

        - ${{ each step in parameters.beforeCopyEnvironmentUsersteps }}:
          - ${{ each pair in step }}:
              ${{ pair.key }}: ${{ pair.value }}

        - ${{ if eq(parameters.backupDestinationEnvironment, true) }}:
          - task: microsoft-IsvExpTools.PowerPlatform-BuildTools.backup-environment.PowerPlatformBackupEnvironment@0
            displayName: 'Power Platform Backup - ${{ parameters.destinationEnvironment.name }}'
            inputs:
              authenticationType: 'PowerPlatformSPN'
              PowerPlatformSPN: '${{ parameters.PowerPlatformSPN }}'
              PowerPlatformEnvironment: '${{ parameters.destinationEnvironment.url }}'
              BackupLabel: 'Full backup - $(Build.BuildNumber)'

        - task: microsoft-IsvExpTools.PowerPlatform-BuildTools.copy-environment.PowerPlatformCopyEnvironment@0
          displayName: 'Power Platform Copy Environment '
          inputs:
            authenticationType: 'PowerPlatformSPN'
            PowerPlatformSPN: '${{ parameters.PowerPlatformSPN }}'
            PowerPlatformEnvironment: '${{ parameters.sourceEnvironment.url }}'
            TargetEnvironmentUrl: '${{ parameters.destinationEnvironment.url }}'
            CopyType: '${{ parameters.CopyType }}'
            DisableAdminMode: '${{ parameters.DisableAdminMode }}'

        - ${{ each step in parameters.afterCopyEnvironmentUsersteps }}:
          - ${{ each pair in step }}:
              ${{ pair.key }}: ${{ pair.value }}